#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Project Euler
# Problem 29
#
# How many distinct terms are in the sequence
# generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

def p029():
    terms = set()
    for a in xrange(2,101):
        for b in xrange(2, 101):
            terms.add(a**b)
    return len(terms)

if __name__=='__main__':
    print p029()
