// Project Euler Problem 029
//
// How many distinct terms are in the sequence generated by a^b for
// 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

#include <cstdio>
#include <set>
#include <string>
#include <sstream>
#include "primes1.h"

using namespace std;

typedef vector<pair<int, int> > pairvector;

string make_string(const pairvector& factors, int exponent) {
  stringstream s;
  for (pairvector::const_iterator it = factors.begin(); it != factors.end(); ++it) {
    s << it->first << '-' << (it->second * exponent) << ' ';
  }
  return s.str();
}

int main(int argc, const char* argv[]) {
  set<string> seen;
  Primes1<int> primes;
  for (int a=2; a<=100; a++) {
    pairvector factors = primes.prime_factors(a);
    for (int b=2; b<=100; b++) {
      seen.insert(make_string(factors, b));
    }
  }
  printf("%zu\n", seen.size());
}
