CPP = g++
OFLAG = -o
CPPFLAGS = -Wall -O3
.SUFFIXES : .o .cpp .c
.cpp.o :
	$(CPP) $(CPPFLAGS) -c $<
.c.o :
	$(CPP) $(CPPFLAGS) -c $<

clean :
	rm -f [0-9][0-9][0-9] *~

bigmath_test: bigmath_test.cc bigmath.h
002: 002.cc mymath.h
003: 003.cc primes1.h
005: 005.cc primes1.h
007: 007.cc primes1.h
010: 010.cc primes1.h
016: 016.cc bigmath.h
020: 020.cc bigmath.h
021: 021.cc primes1.h
023: 023.cc primes1.h
025: 025.cc bigmath.h
027: 027.cc primes1.h
029: 029.cc primes1.h
033: 033.cc mymath.h
