CPP = g++
OFLAG = -o
CPPFLAGS = -Wall
.SUFFIXES : .o .cpp .c
.cpp.o :
	$(CPP) $(CPPFLAGS) -c $<
.c.o :
	$(CPP) $(CPPFLAGS) -c $<

002: 002.cc fib.h
003: 003.cc primes1.h
005: 005.cc primes1.h
007: 007.cc primes1.h
010: 010.cc primes1.h
