// Project Euler Problem 029
//
// How many distinct terms are in the sequence generated by a^b for
// 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

package problems

import "fmt"

func Problem029() string {
	return fmt.Sprintf("%d", 0)
}

func init() {
     Functions[29] = Problem029
}
